apiVersion: v1
kind: Service
metadata:
  name: hotel-backend-service
  namespace: dev
spec:
  selector:
    app: hotel-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP