apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-backend
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-backend
  template:
    metadata:
      labels:
        app: hotel-backend
    spec:
      containers:
      - name: backend
        image: manishapasandul/hotel-backend:1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"