apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: frontend
        image: manishapasandul/hotel-frontend:latest
        ports:
        - containerPort: 3000