apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: frontend
        image: manishapasandul/hotel-booking-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://hotel-backend-service:5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"