apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-frontend
  template:
    metadata:
      labels:
        app: hotel-frontend
    spec:
      containers:
      - name: frontend
        image: manishapasandul/hotel-frontend:1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"